python demo.py a > a.log 2>&1 &
python demo.py b > b.log 2>&1 &
python demo.py c > c.log 2>&1 &
python demo.py d > d.log 2>&1 &
python demo.py e > e.log 2>&1 &
python demo.py f > f.log 2>&1 &
python demo.py g > g.log 2>&1 &
python demo.py h > h.log 2>&1 &
python demo.py m > m.log 2>&1 &
python demo.py x > x.log 2>&1 &
python demo.py y > y.log 2>&1 &
python demo.py z > z.log 2>&1 &
python demo.py v > v.log 2>&1 &
